apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: wordpress-enterprise
spec:
  chart:
    name: wordpress-enterprise
    chartVersion: $VERSION
  helmVersion: v3
  useHelmInstall: false
  values:
    isKurl: repl{{ IsKurl }}
    replicated:
      enabled: false
    nginx:
      image: dexhorthy/kotsadm-api
      tag: nginx
    fake: yep
    config: 
      exampleDefaultValue: repl{{ ConfigOption "example_default_value" }}
      hiddenValue: repl{{ ConfigOption "hidden_text" }}
